config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
  get "/reviews", to: "reviews#index"
  resources :movies, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates_format_of :user_email, with: VALID_EMAIL_REGEX, message: "is not a valid email address"
  validates_numericality_of :rating, greater_than_or_equal_to: 0, less_than_or_equal_to: 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies_by_genre = MoviesList.new.movies_by_genre
  end

  def show
    @title = params[:movie_title]
    @reviews = Review.where(movie_id: params[:id])
  end

  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
    @title = params[:movie_title]
  end

  def create
    @review = Review.new(review_params)
    @title ||= params[:review][:movie_title]

    if @review.save
      redirect_to movies_path, notice: "Your movie review has been submitted."
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:user_email, :rating, :comment, :movie_id, :movie_title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def panel_row(label, data)
    content_tag(:p) do
      content_tag(:span, label, class: "strong") + ": " + data
    end
  end

  def extract_date(datetime)
    datetime.strftime("%Y-%m-%d")
  end

end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Cinerate', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Cinerate'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Cinerate'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield
    .footer
      = "This product uses the #{link_to 'TMDb', 'http://www.themoviedb.org'} API but is not endorsed or certified by #{link_to 'TMDb', 'http://www.themoviedb.org'}.".html_safe

app/views/movies/index.html.haml
%h2 Movies
.read-all
  = link_to "Read All Movie Reviews", reviews_path, class: "btn btn-primary"
%table#movies_table.table.tablesorter.tablesorter-blue
  %thead
    %tr
      %th Title
      %th Release Date
      %th Genre
      %th
      %th
  %tbody
    - @movies_by_genre.each do |genre, movies|
      - movies.each do |movie|
        %tr
          %td
            = movie["title"]
          %td
            = movie["release_date"]
          %td
            = genre
          %td
            = link_to "Read Reviews", movie_path(movie["id"], movie_title: movie["title"])
          %td
            = link_to "New Review", new_movie_review_path(movie["id"], movie_title: movie["title"])

app/views/movies/show.html.haml
%h2
  = "Reviews for #{@title}"
-if @reviews.any?
  - @reviews.each do |review|
    .panel.panel-primary
      = render "shared/review_panel", review: review
-else
  %p There are no reviews yet. Be the first!
= link_to "Write a Review", new_movie_review_path(params[:id], movie_title: params[:movie_title]), class: "btn btn-primary"

app/views/reviews/index.html.haml
%h2 All Movie Reviews
- @reviews.each do |review|
  .panel.panel-primary
    .panel-heading
      = review.movie_title
    = render "shared/review_panel", review: review

app/views/reviews/new.html.haml
%h2
  = "New Review for #{@title}"
%h3
= simple_form_for @review, url: movie_reviews_path do |f|
  = f.error_notification
  = f.hidden_field :movie_id, value: params[:movie_id]
  = f.hidden_field :movie_title, value: @title
  = f.input :user_email, label: "Email Address", required: true, input_html: { style: "width: 500px" }
  = f.input :rating, label: "Rating (from 0 to 10)", required: true, as: :select, collection: (0..10), input_html: { style: "width: 100px" }
  = f.input :comment, as: :text, input_html: { style: "width: 500px" }
  = f.submit "Submit Review", class: "btn btn-primary"

app/views/shared/_review_panel.html.haml
.panel-body
  = panel_row("Email Address", review.user_email)
  = panel_row("Review Date", extract_date(review.created_at))
  = panel_row("Rating (out of 10)", review.rating.to_s)
  = panel_row("Comment", review.comment) if review.comment.present?